version: "3.5"
services:
  nginx:
    environment:
      - NGINX_PUBLIC=/public

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    build:
      context: ./.warden/.docker/fpm/
      args:
        PHP_VERSION: ${PHP_VERSION}
        WARDEN_IMAGE_REPOSITORY: ${WARDEN_IMAGE_REPOSITORY}
    volumes:
      - ./.warden/php/config.ini:/etc/php.d/config.ini

  php-debug:
    depends_on:
      - php-fpm
    build:
      context: ./.warden/.docker/debug/
      args:
        PHP_VERSION: ${PHP_VERSION}
        WARDEN_IMAGE_REPOSITORY: ${WARDEN_IMAGE_REPOSITORY}
        XDEBUG_VERSION: ${XDEBUG_VERSION}
    volumes:
      - ./.warden/php/config.ini:/etc/php.d/config.ini

  db:
    hostname: "${WARDEN_ENV_NAME}-postgres"
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}